apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  template:
    metadata:
      name: notification
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: odoraf/notification:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: SPRING_DATASOURCE_USERNAME
              value: linpostgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: DB_PASSWORD
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://lin-24718-9092-pgsql-primary.servers.linodedb.net/notification
      restartPolicy: Always
  selector:
    matchLabels:
      app: notification
