apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
  labels:
    app: fraud
spec:
  replicas: 1
  template:
    metadata:
      name: fraud
      labels:
        app: fraud
    spec:
      containers:
        - name: fraud
          image: odoraf/fraud:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: SPRING_DATASOURCE_USERNAME
              value: linpostgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: DB_PASSWORD
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://lin-24718-9092-pgsql-primary.servers.linodedb.net/fraud
      restartPolicy: Always
  selector:
    matchLabels:
      app: fraud
